import type { Metadata } from "next";
import Script from "next/script";

import { poppins } from "../assets/fonts/font";
import GtagProvider from "../shared/lib/google-tag/GoogleTagProvider";
import NextProgressBar from "../shared/lib/next-progress/NextProgressProvider";
import QueryClientProviderWrapper from "../shared/lib/react-query/QueryClientProvider";
import ToastProvider from "../shared/lib/toast/ToastProvider";
import "./globals.css";
import "./lib.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`antialiased ${poppins.className}`}>
        <NextProgressBar />
        <QueryClientProviderWrapper>{children}</QueryClientProviderWrapper>
        <ToastProvider />
        <GtagProvider />
        <Script
          id="tawk-script"
          strategy="afterInteractive"
          dangerouslySetInnerHTML={{
            __html: `
            var Tawk_API=Tawk_API||{}, Tawk_LoadStart=new Date();
            (function(){
             var s1=document.createElement("script"),s0=document.getElementsByTagName("script")[0];
             s1.async=true;
             s1.src = "https://embed.tawk.to/${process.env.NEXT_PUBLIC_TAWK_PROPERTY_ID}";
             s1.charset='UTF-8';
             s1.setAttribute('crossorigin','*');
             s0.parentNode.insertBefore(s1,s0);
        })();
          `,
          }}
        />
      </body>
    </html>
  );
}
