export const contactUsServicesConstants = [
  {
    id: 1,
    title: "Web Development",
  },
  {
    id: 2,
    title: "Mobile App Development",
  },
  {
    id: 3,
    title: "DevOps",
  },
  {
    id: 4,
    title: "AI Integration",
  },
  {
    id: 5,
    title: "Machine Learning Development",
  },
  {
    id: 6,
    title: "Quality Assurance",
  },
  {
    id: 7,
    title: "Technical Assessment",
  },
  {
    id: 8,
    title: "Support & Maintenance",
  },
  {
    id: 9,
    title: "Outstaffing",
  },
  {
    id: 10,
    title: "Project Management",
  },
  {
    id: 11,
    title: "UI/UX Design",
  },
  {
    id: 12,
    title: "Digital Marketing",
  },
];

export const contactUsCountriesConstants = [
  { id: 1, title: "Afghanistan" },
  { id: 2, title: "Albania" },
  { id: 3, title: "Algeria" },
  { id: 4, title: "American Samoa" },
  { id: 5, title: "Andorra" },
  { id: 6, title: "Angola" },
  { id: 7, title: "Anguilla" },
  { id: 8, title: "Antarctica" },
  { id: 9, title: "Antigua and Barbuda" },
  { id: 10, title: "Argentina" },
  { id: 11, title: "Armenia" },
  { id: 12, title: "Aruba" },
  { id: 13, title: "Australia" },
  { id: 14, title: "Austria" },
  { id: 15, title: "Azerbaijan" },
  { id: 16, title: "Bahamas (the)" },
  { id: 17, title: "Bahrain" },
  { id: 18, title: "Bangladesh" },
  { id: 19, title: "Barbados" },
  { id: 20, title: "Belarus" },
  { id: 21, title: "Belgium" },
  { id: 22, title: "Belize" },
  { id: 23, title: "Benin" },
  { id: 24, title: "Bermuda" },
  { id: 25, title: "Bhutan" },
  { id: 26, title: "Bolivia (Plurinational State of)" },
  { id: 27, title: "Bonaire, Sint Eustatius and Saba" },
  { id: 28, title: "Bosnia and Herzegovina" },
  { id: 29, title: "Botswana" },
  { id: 30, title: "Bouvet Island" },
  { id: 31, title: "Brazil" },
  { id: 32, title: "British Indian Ocean Territory (the)" },
  { id: 33, title: "Brunei Darussalam" },
  { id: 34, title: "Bulgaria" },
  { id: 35, title: "Burkina Faso" },
  { id: 36, title: "Burundi" },
  { id: 37, title: "Cabo Verde" },
  { id: 38, title: "Cambodia" },
  { id: 39, title: "Cameroon" },
  { id: 40, title: "Canada" },
  { id: 41, title: "Cayman Islands (the)" },
  { id: 42, title: "Central African Republic (the)" },
  { id: 43, title: "Chad" },
  { id: 44, title: "Chile" },
  { id: 45, title: "China" },
  { id: 46, title: "Christmas Island" },
  { id: 47, title: "Cocos (Keeling) Islands (the)" },
  { id: 48, title: "Colombia" },
  { id: 49, title: "Comoros (the)" },
  { id: 50, title: "Congo (the Democratic Republic of the)" },
  { id: 51, title: "Congo (the)" },
  { id: 52, title: "Cook Islands (the)" },
  { id: 53, title: "Costa Rica" },
  { id: 54, title: "Croatia" },
  { id: 55, title: "Cuba" },
  { id: 56, title: "Curaçao" },
  { id: 57, title: "Cyprus" },
  { id: 58, title: "Czechia" },
  { id: 59, title: "Côte d'Ivoire" },
  { id: 60, title: "Denmark" },
  { id: 61, title: "Djibouti" },
  { id: 62, title: "Dominica" },
  { id: 63, title: "Dominican Republic (the)" },
  { id: 64, title: "Ecuador" },
  { id: 65, title: "Egypt" },
  { id: 66, title: "El Salvador" },
  { id: 67, title: "Equatorial Guinea" },
  { id: 68, title: "Eritrea" },
  { id: 69, title: "Estonia" },
  { id: 70, title: "Eswatini" },
  { id: 71, title: "Ethiopia" },
  { id: 72, title: "Falkland Islands (the) [Malvinas]" },
  { id: 73, title: "Faroe Islands (the)" },
  { id: 74, title: "Fiji" },
  { id: 75, title: "Finland" },
  { id: 76, title: "France" },
  { id: 77, title: "French Guiana" },
  { id: 78, title: "French Polynesia" },
  { id: 79, title: "French Southern Territories (the)" },
  { id: 80, title: "Gabon" },
  { id: 81, title: "Gambia (the)" },
  { id: 82, title: "Georgia" },
  { id: 83, title: "Germany" },
  { id: 84, title: "Ghana" },
  { id: 85, title: "Gibraltar" },
  { id: 86, title: "Greece" },
  { id: 87, title: "Greenland" },
  { id: 88, title: "Grenada" },
  { id: 89, title: "Guadeloupe" },
  { id: 90, title: "Guam" },
  { id: 91, title: "Guatemala" },
  { id: 92, title: "Guernsey" },
  { id: 93, title: "Guinea" },
  { id: 94, title: "Guinea-Bissau" },
  { id: 95, title: "Guyana" },
  { id: 96, title: "Haiti" },
  { id: 97, title: "Heard Island and McDonald Islands" },
  { id: 98, title: "Holy See (the)" },
  { id: 99, title: "Honduras" },
  { id: 100, title: "Hong Kong" },
  { id: 101, title: "Hungary" },
  { id: 102, title: "Iceland" },
  { id: 103, title: "India" },
  { id: 104, title: "Indonesia" },
  { id: 105, title: "Iran (Islamic Republic of)" },
  { id: 106, title: "Iraq" },
  { id: 107, title: "Ireland" },
  { id: 108, title: "Isle of Man" },
  { id: 109, title: "Israel" },
  { id: 110, title: "Italy" },
  { id: 111, title: "Jamaica" },
  { id: 112, title: "Japan" },
  { id: 113, title: "Jersey" },
  { id: 114, title: "Jordan" },
  { id: 115, title: "Kazakhstan" },
  { id: 116, title: "Kenya" },
  { id: 117, title: "Kiribati" },
  { id: 118, title: "Korea (the Democratic People's Republic of)" },
  { id: 119, title: "Korea (the Republic of)" },
  { id: 120, title: "Kuwait" },
  { id: 121, title: "Kyrgyzstan" },
  { id: 122, title: "Lao People's Democratic Republic (the)" },
  { id: 123, title: "Latvia" },
  { id: 124, title: "Lebanon" },
  { id: 125, title: "Lesotho" },
  { id: 126, title: "Liberia" },
  { id: 127, title: "Libya" },
  { id: 128, title: "Liechtenstein" },
  { id: 129, title: "Lithuania" },
  { id: 130, title: "Luxembourg" },
  { id: 131, title: "Macao" },
  { id: 132, title: "Madagascar" },
  { id: 133, title: "Malawi" },
  { id: 134, title: "Malaysia" },
  { id: 135, title: "Maldives" },
  { id: 136, title: "Mali" },
  { id: 137, title: "Malta" },
  { id: 138, title: "Marshall Islands (the)" },
  { id: 139, title: "Martinique" },
  { id: 140, title: "Mauritania" },
  { id: 141, title: "Mauritius" },
  { id: 142, title: "Mayotte" },
  { id: 143, title: "Mexico" },
  { id: 144, title: "Micronesia (Federated States of)" },
  { id: 145, title: "Moldova (the Republic of)" },
  { id: 146, title: "Monaco" },
  { id: 147, title: "Mongolia" },
  { id: 148, title: "Montenegro" },
  { id: 149, title: "Montserrat" },
  { id: 150, title: "Morocco" },
  { id: 151, title: "Mozambique" },
  { id: 152, title: "Myanmar" },
  { id: 153, title: "Namibia" },
  { id: 154, title: "Nauru" },
  { id: 155, title: "Nepal" },
  { id: 156, title: "Netherlands (the)" },
  { id: 157, title: "New Caledonia" },
  { id: 158, title: "New Zealand" },
  { id: 159, title: "Nicaragua" },
  { id: 160, title: "Niger (the)" },
  { id: 161, title: "Nigeria" },
  { id: 162, title: "Niue" },
  { id: 163, title: "Norfolk Island" },
  { id: 164, title: "Northern Mariana Islands (the)" },
  { id: 165, title: "Norway" },
  { id: 166, title: "Oman" },
  { id: 167, title: "Pakistan" },
  { id: 168, title: "Palau" },
  { id: 169, title: "Palestine, State of" },
  { id: 170, title: "Panama" },
  { id: 171, title: "Papua New Guinea" },
  { id: 172, title: "Paraguay" },
  { id: 173, title: "Peru" },
  { id: 174, title: "Philippines (the)" },
  { id: 175, title: "Pitcairn" },
  { id: 176, title: "Poland" },
  { id: 177, title: "Portugal" },
  { id: 178, title: "Puerto Rico" },
  { id: 179, title: "Qatar" },
  { id: 180, title: "Republic of North Macedonia" },
  { id: 181, title: "Romania" },
  { id: 182, title: "Russian Federation (the)" },
  { id: 183, title: "Rwanda" },
  { id: 184, title: "Réunion" },
  { id: 185, title: "Saint Barthélemy" },
  { id: 186, title: "Saint Helena, Ascension and Tristan da Cunha" },
  { id: 187, title: "Saint Kitts and Nevis" },
  { id: 188, title: "Saint Lucia" },
  { id: 189, title: "Saint Martin (French part)" },
  { id: 190, title: "Saint Pierre and Miquelon" },
  { id: 191, title: "Saint Vincent and the Grenadines" },
  { id: 192, title: "Samoa" },
  { id: 193, title: "San Marino" },
  { id: 194, title: "Sao Tome and Principe" },
  { id: 195, title: "Saudi Arabia" },
  { id: 196, title: "Senegal" },
  { id: 197, title: "Serbia" },
  { id: 198, title: "Seychelles" },
  { id: 199, title: "Sierra Leone" },
  { id: 200, title: "Singapore" },
  { id: 201, title: "Sint Maarten (Dutch part)" },
  { id: 202, title: "Slovakia" },
  { id: 203, title: "Slovenia" },
  { id: 204, title: "Solomon Islands" },
  { id: 205, title: "Somalia" },
  { id: 206, title: "South Africa" },
  { id: 207, title: "South Georgia and the South Sandwich Islands" },
  { id: 208, title: "South Sudan" },
  { id: 209, title: "Spain" },
  { id: 210, title: "Sri Lanka" },
  { id: 211, title: "Sudan (the)" },
  { id: 212, title: "Suriname" },
  { id: 213, title: "Svalbard and Jan Mayen" },
  { id: 214, title: "Sweden" },
  { id: 215, title: "Switzerland" },
  { id: 216, title: "Syrian Arab Republic" },
  { id: 217, title: "Taiwan" },
  { id: 218, title: "Tajikistan" },
  { id: 219, title: "Tanzania, United Republic of" },
  { id: 220, title: "Thailand" },
  { id: 221, title: "Timor-Leste" },
  { id: 222, title: "Togo" },
  { id: 223, title: "Tokelau" },
  { id: 224, title: "Tonga" },
  { id: 225, title: "Trinidad and Tobago" },
  { id: 226, title: "Tunisia" },
  { id: 227, title: "Turkey" },
  { id: 228, title: "Turkmenistan" },
  { id: 229, title: "Turks and Caicos Islands (the)" },
  { id: 230, title: "Tuvalu" },
  { id: 231, title: "Uganda" },
  { id: 232, title: "Ukraine" },
  { id: 233, title: "United Arab Emirates (the)" },
  { id: 234, title: "United Kingdom of Great Britain and Northern Ireland (the)" },
  { id: 235, title: "United States Minor Outlying Islands (the)" },
  { id: 236, title: "United States of America (the)" },
  { id: 237, title: "Uruguay" },
  { id: 238, title: "Uzbekistan" },
  { id: 239, title: "Vanuatu" },
  { id: 240, title: "Venezuela (Bolivarian Republic of)" },
  { id: 241, title: "Viet Nam" },
  { id: 242, title: "Virgin Islands (British)" },
  { id: 243, title: "Virgin Islands (U.S.)" },
  { id: 244, title: "Wallis and Futuna" },
  { id: 245, title: "Western Sahara" },
  { id: 246, title: "Yemen" },
  { id: 247, title: "Zambia" },
  { id: 248, title: "Zimbabwe" },
  { id: 249, title: "Åland Islands" },
];
