import Blog1 from "@/assets/images/blogs/Blog1.webp";
import Blog2 from "@/assets/images/blogs/Blog2.webp";

export const blogsConstants = [
  {
    id: "1",
    description: "How to Start with Medicine Delivery App Development in 2024",
    date: new Date("12/04/2024"),
    image: Blog1,
    imageAlt: "Lorem ipsum dolor sit amet, consectetur adip",
    readingTime: "12 Min",
  },
  {
    id: "2",
    description: "iOS App Development: Top Practices, Tools, & Benefits",
    date: new Date("12/04/2024"),
    image: Blog2,
    imageAlt: "Lorem ipsum dolor sit amet, consectetur adip",
    readingTime: "12 Min",
  },
  {
    id: "3",
    description: "Mobile App Development: Top Practices, Tools, & Benefits",
    date: new Date("12/04/2024"),
    image: Blog2,
    imageAlt: "Lorem ipsum dolor sit amet, consectetur adip",
    readingTime: "12 Min",
  },
  {
    id: "4",
    description: "Best Countries To Outsource Software Development in 2024",
    date: new Date("12/04/2024"),
    image: Blog2,
    readingTime: "12 Min",
  },
  {
    id: "5",
    description: "How Much Does it Cost to Create On Demand Marketplace",
    date: new Date("12/04/2024"),
    image: Blog2,
    imageAlt: "Lorem ipsum dolor sit amet, consectetur adip",
    readingTime: "12 Min",
  },
  {
    id: "6",
    description: "Mobile App vs. Web App: Which Is Right for Your Business",
    date: new Date("12/04/2024"),
    image: Blog2,
    imageAlt: "Lorem ipsum dolor sit amet, consectetur adip",
    readingTime: "12 Min",
  },
  {
    id: "7",
    description: "How to Start with Medicine Delivery App Development in 2024",
    date: new Date("12/04/2024"),
    image: Blog2,
    readingTime: "12 Min",
  },
  {
    id: "8",
    description: "IOS App Development: Top Practices, Tools, & Benefits",
    date: new Date("12/04/2024"),
    image: Blog2,
    imageAlt: "Lorem ipsum dolor sit amet, consectetur adip",
    readingTime: "12 Min",
  },
  {
    id: "9",
    description: "Mobile App Development: Top Practices, Tools, & Benefits",
    date: new Date("12/04/2024"),
    image: Blog2,
    imageAlt: "Lorem ipsum dolor sit amet, consectetur adip",
    readingTime: "12 Min",
  },
];
