export const industriesConstants = [
  [
    "Media and Entertainment",
    "Film Production",
    "Commercial Advertising",
    "Music Production and Sound Design",
    "Technology and Software Development",
    "Event Planning and Management",
    "Hospitality",
    "Online Booking Platforms",
    "Virtual Meetings and Conferencing",
    "Mobile Application Development",
    "Information Technology (IT) Services",
    "Managed Service Providers (MSPs)",
    "Cybersecurity",
    "Digital Transformation",
    "Logistics and Transportation",
    "Freight and Cargo Services",
  ],
  [
    "Passenger Transportation",
    "Supply Chain Management",
    "Artificial Intelligence (AI)",
    "Software as a Service (SaaS)",
    "Data Integration",
    "Data Analytics",
    "Dashboard Development",
    "Online Content Creation",
    "Storytelling Platforms",
    "Collaboration Tools",
    "Task Management Systems",
    "Human Resources (HR)",
    "Performance Management",
    "Employee Evaluation",
    "Bonus Calculation",
    "Automation and Workflow Tools",
  ],
  [
    "Recruitment and Staffing",
    "Career Development",
    "Education and Training",
    "Online Platforms",
    "Healthcare Technology",
    "Medical Software Development",
    "Clinic and Lab Management",
    "Digital Health Solutions",
    "Telemedicine",
    "COVID-19 Testing and Monitoring",
    "Appointment Scheduling",
    "Treatment Management",
    "Regenerative Medicine",
    "Underwriting",
    "Landing",
    "Insurance",
  ],
];
